"""Add site add_col column

Revision ID: 318b8873ea67
Revises: 637a9611f663
Create Date: 2023-07-09 09:37:19.065834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '318b8873ea67'
down_revision = '637a9611f663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_visits', sa.Column('add_coll', sa.String(), nullable=True))
    op.drop_column('site_visits', 'add_col')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_visits', sa.Column('add_col', sa.VARCHAR(), nullable=True))
    op.drop_column('site_visits', 'add_coll')
    # ### end Alembic commands ###
